name: acp_dart
description: A sample command-line application.
version: 0.1.0
repository: https://github.com/SkrOYC/acp-dart

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.8.0
  json_serializable: ^6.11.1
  lints: ^6.0.0
  test: ^1.25.6
